/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PmRouteImport } from './routes/pm'
import { Route as EmployeeDashboardRouteImport } from './routes/employee.dashboard'
import { Route as PmAiHubRouteImport } from './routes/pm.ai-hub'
import { Route as PmCapacityRouteImport } from './routes/pm.capacity'
import { Route as PmDashboardRouteImport } from './routes/pm.dashboard'
import { Route as PmEmployeesRouteImport } from './routes/pm.employees'
import { Route as PmRolesRouteImport } from './routes/pm.roles'
import { Route as PmEmployeesEmployeeIdRouteImport } from './routes/pm.employees.$employeeId'
import { Route as PmProjectsIndexRouteImport } from './routes/pm.projects.index'
import { Route as PmProjectsProjectIdRouteImport } from './routes/pm.projects.$projectId'
import { Route as EmployeeTasksTaskIdLogRouteImport } from './routes/employee.tasks.$taskId.log'
import { Route as PmProjectsProjectIdMatrixRouteImport } from './routes/pm.projects.$projectId.matrix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRoute = PmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const PmAiHubRoute = PmAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => PmRoute,
} as any)
const PmCapacityRoute = PmCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => PmRoute,
} as any)
const PmDashboardRoute = PmDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PmRoute,
} as any)
const PmEmployeesRoute = PmEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => PmRoute,
} as any)
const PmRolesRoute = PmRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => PmRoute,
} as any)
const PmEmployeesEmployeeIdRoute = PmEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => PmEmployeesRoute,
} as any)
const PmProjectsIndexRoute = PmProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PmRoute,
} as any)
const PmProjectsProjectIdRoute = PmProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => PmRoute,
} as any)
const EmployeeTasksTaskIdLogRoute = EmployeeTasksTaskIdLogRouteImport.update({
  id: '/tasks/$taskId/log',
  path: '/tasks/$taskId/log',
  getParentRoute: () => EmployeeRoute,
} as any)
const PmProjectsProjectIdMatrixRoute =
  PmProjectsProjectIdMatrixRouteImport.update({
    id: '/matrix',
    path: '/matrix',
    getParentRoute: () => PmProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/pm': typeof PmRouteWithChildren
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/pm/ai-hub': typeof PmAiHubRoute
  '/pm/capacity': typeof PmCapacityRoute
  '/pm/dashboard': typeof PmDashboardRoute
  '/pm/employees': typeof PmEmployeesRouteWithChildren
  '/pm/roles': typeof PmRolesRoute
  '/pm/employees/$employeeId': typeof PmEmployeesEmployeeIdRoute
  '/pm/projects/$projectId': typeof PmProjectsProjectIdRouteWithChildren
  '/pm/projects/': typeof PmProjectsIndexRoute
  '/employee/tasks/$taskId/log': typeof EmployeeTasksTaskIdLogRoute
  '/pm/projects/$projectId/matrix': typeof PmProjectsProjectIdMatrixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/pm': typeof PmRouteWithChildren
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/pm/ai-hub': typeof PmAiHubRoute
  '/pm/capacity': typeof PmCapacityRoute
  '/pm/dashboard': typeof PmDashboardRoute
  '/pm/employees': typeof PmEmployeesRouteWithChildren
  '/pm/roles': typeof PmRolesRoute
  '/pm/employees/$employeeId': typeof PmEmployeesEmployeeIdRoute
  '/pm/projects/$projectId': typeof PmProjectsProjectIdRouteWithChildren
  '/pm/projects': typeof PmProjectsIndexRoute
  '/employee/tasks/$taskId/log': typeof EmployeeTasksTaskIdLogRoute
  '/pm/projects/$projectId/matrix': typeof PmProjectsProjectIdMatrixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/pm': typeof PmRouteWithChildren
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/pm/ai-hub': typeof PmAiHubRoute
  '/pm/capacity': typeof PmCapacityRoute
  '/pm/dashboard': typeof PmDashboardRoute
  '/pm/employees': typeof PmEmployeesRouteWithChildren
  '/pm/roles': typeof PmRolesRoute
  '/pm/employees/$employeeId': typeof PmEmployeesEmployeeIdRoute
  '/pm/projects/$projectId': typeof PmProjectsProjectIdRouteWithChildren
  '/pm/projects/': typeof PmProjectsIndexRoute
  '/employee/tasks/$taskId/log': typeof EmployeeTasksTaskIdLogRoute
  '/pm/projects/$projectId/matrix': typeof PmProjectsProjectIdMatrixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/login'
    | '/pm'
    | '/employee/dashboard'
    | '/pm/ai-hub'
    | '/pm/capacity'
    | '/pm/dashboard'
    | '/pm/employees'
    | '/pm/roles'
    | '/pm/employees/$employeeId'
    | '/pm/projects/$projectId'
    | '/pm/projects/'
    | '/employee/tasks/$taskId/log'
    | '/pm/projects/$projectId/matrix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employee'
    | '/login'
    | '/pm'
    | '/employee/dashboard'
    | '/pm/ai-hub'
    | '/pm/capacity'
    | '/pm/dashboard'
    | '/pm/employees'
    | '/pm/roles'
    | '/pm/employees/$employeeId'
    | '/pm/projects/$projectId'
    | '/pm/projects'
    | '/employee/tasks/$taskId/log'
    | '/pm/projects/$projectId/matrix'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/login'
    | '/pm'
    | '/employee/dashboard'
    | '/pm/ai-hub'
    | '/pm/capacity'
    | '/pm/dashboard'
    | '/pm/employees'
    | '/pm/roles'
    | '/pm/employees/$employeeId'
    | '/pm/projects/$projectId'
    | '/pm/projects/'
    | '/employee/tasks/$taskId/log'
    | '/pm/projects/$projectId/matrix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  LoginRoute: typeof LoginRoute
  PmRoute: typeof PmRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/pm/ai-hub': {
      id: '/pm/ai-hub'
      path: '/ai-hub'
      fullPath: '/pm/ai-hub'
      preLoaderRoute: typeof PmAiHubRouteImport
      parentRoute: typeof PmRoute
    }
    '/pm/capacity': {
      id: '/pm/capacity'
      path: '/capacity'
      fullPath: '/pm/capacity'
      preLoaderRoute: typeof PmCapacityRouteImport
      parentRoute: typeof PmRoute
    }
    '/pm/dashboard': {
      id: '/pm/dashboard'
      path: '/dashboard'
      fullPath: '/pm/dashboard'
      preLoaderRoute: typeof PmDashboardRouteImport
      parentRoute: typeof PmRoute
    }
    '/pm/employees': {
      id: '/pm/employees'
      path: '/employees'
      fullPath: '/pm/employees'
      preLoaderRoute: typeof PmEmployeesRouteImport
      parentRoute: typeof PmRoute
    }
    '/pm/roles': {
      id: '/pm/roles'
      path: '/roles'
      fullPath: '/pm/roles'
      preLoaderRoute: typeof PmRolesRouteImport
      parentRoute: typeof PmRoute
    }
    '/pm/employees/$employeeId': {
      id: '/pm/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/pm/employees/$employeeId'
      preLoaderRoute: typeof PmEmployeesEmployeeIdRouteImport
      parentRoute: typeof PmEmployeesRoute
    }
    '/pm/projects/': {
      id: '/pm/projects/'
      path: '/projects'
      fullPath: '/pm/projects/'
      preLoaderRoute: typeof PmProjectsIndexRouteImport
      parentRoute: typeof PmRoute
    }
    '/pm/projects/$projectId': {
      id: '/pm/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/pm/projects/$projectId'
      preLoaderRoute: typeof PmProjectsProjectIdRouteImport
      parentRoute: typeof PmRoute
    }
    '/employee/tasks/$taskId/log': {
      id: '/employee/tasks/$taskId/log'
      path: '/tasks/$taskId/log'
      fullPath: '/employee/tasks/$taskId/log'
      preLoaderRoute: typeof EmployeeTasksTaskIdLogRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/pm/projects/$projectId/matrix': {
      id: '/pm/projects/$projectId/matrix'
      path: '/matrix'
      fullPath: '/pm/projects/$projectId/matrix'
      preLoaderRoute: typeof PmProjectsProjectIdMatrixRouteImport
      parentRoute: typeof PmProjectsProjectIdRoute
    }
  }
}

interface EmployeeRouteChildren {
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeTasksTaskIdLogRoute: typeof EmployeeTasksTaskIdLogRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeTasksTaskIdLogRoute: EmployeeTasksTaskIdLogRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface PmEmployeesRouteChildren {
  PmEmployeesEmployeeIdRoute: typeof PmEmployeesEmployeeIdRoute
}

const PmEmployeesRouteChildren: PmEmployeesRouteChildren = {
  PmEmployeesEmployeeIdRoute: PmEmployeesEmployeeIdRoute,
}

const PmEmployeesRouteWithChildren = PmEmployeesRoute._addFileChildren(
  PmEmployeesRouteChildren,
)

interface PmProjectsProjectIdRouteChildren {
  PmProjectsProjectIdMatrixRoute: typeof PmProjectsProjectIdMatrixRoute
}

const PmProjectsProjectIdRouteChildren: PmProjectsProjectIdRouteChildren = {
  PmProjectsProjectIdMatrixRoute: PmProjectsProjectIdMatrixRoute,
}

const PmProjectsProjectIdRouteWithChildren =
  PmProjectsProjectIdRoute._addFileChildren(PmProjectsProjectIdRouteChildren)

interface PmRouteChildren {
  PmAiHubRoute: typeof PmAiHubRoute
  PmCapacityRoute: typeof PmCapacityRoute
  PmDashboardRoute: typeof PmDashboardRoute
  PmEmployeesRoute: typeof PmEmployeesRouteWithChildren
  PmRolesRoute: typeof PmRolesRoute
  PmProjectsProjectIdRoute: typeof PmProjectsProjectIdRouteWithChildren
  PmProjectsIndexRoute: typeof PmProjectsIndexRoute
}

const PmRouteChildren: PmRouteChildren = {
  PmAiHubRoute: PmAiHubRoute,
  PmCapacityRoute: PmCapacityRoute,
  PmDashboardRoute: PmDashboardRoute,
  PmEmployeesRoute: PmEmployeesRouteWithChildren,
  PmRolesRoute: PmRolesRoute,
  PmProjectsProjectIdRoute: PmProjectsProjectIdRouteWithChildren,
  PmProjectsIndexRoute: PmProjectsIndexRoute,
}

const PmRouteWithChildren = PmRoute._addFileChildren(PmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  LoginRoute: LoginRoute,
  PmRoute: PmRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
